"""empty message

Revision ID: 2cb4c5dd40e0
Revises: 
Create Date: 2018-01-28 16:13:36.320319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb4c5dd40e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('userState', sa.Enum('Nameless', 'NameStaging', 'Ready', 'Conversing', 'Invalid', name='userstate'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userFirstId', sa.String(length=60), nullable=False),
    sa.Column('userSecondId', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['userFirstId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userSecondId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'userFirstId', 'userSecondId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
