"""empty message

Revision ID: c32bf13bd2e3
Revises: 
Create Date: 2018-02-04 18:11:50.389703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32bf13bd2e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('userName', sa.String(length=60), nullable=True),
    sa.Column('nickName', sa.String(length=60), nullable=True),
    sa.Column('userState', sa.Enum('Nameless', 'NameStaging', 'Ready', 'Conversing', 'Invalid', name='userstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userFirstId', sa.String(length=60), nullable=False),
    sa.Column('userSecondId', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userFirstId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userSecondId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversationmessages',
    sa.Column('conversationId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversationId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversationmessages')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
